name: AdvancedWelcomeTitle
version: '${project.version}'
main: de.grubabua.advancedwelcometitle.AdvancedWelcomeTitle
api-version: '1.21'
authors: [grubabua]
website: https://github.com/CodedByGruba

commands:
  setFirsttitle:
    description: Set Your First Title
    aliases:
  setSecondTitle:
    description:  Set Your Second Title
    aliases:
  setPlayerColor:
    description: Set Player Color
    aliases:
  gradientList:
    description: Show Gradient List
    aliases:
  playerJoinMessage:
    description: Turn Join Message on/off
    aliases:
  permission:
    advancedwelcometitle.admin:
      description: "Permission for all Advanced Welcome Title commands"
    advancedwelcometitle.command.setFirstTitle:
      description: "Permission for /setFirstTitle"
    advancedwelcometitle.command.setSecondTitle:
      description: "Permission for /setSecondTitle"
    advancedwelcometitle.command.setPlayerColor:
      description: "Permission for /setPlayerColor"
    advancedwelcometitle.command.gradientList:
      description: "Permission for /gradientList"